# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountinfo',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='accountinfo',
            name='sysname',
        ),
        migrations.RemoveField(
            model_name='checktask',
            name='checktasktimeset',
        ),
        migrations.RemoveField(
            model_name='checktask',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='checktaskdetail',
            name='checktask',
        ),
        migrations.RemoveField(
            model_name='checktaskdetail',
            name='checktemplate',
        ),
        migrations.RemoveField(
            model_name='checktaskdetail',
            name='dbcluster',
        ),
        migrations.RemoveField(
            model_name='checktaskdetail',
            name='dbinstance',
        ),
        migrations.RemoveField(
            model_name='checktemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='checktemplate',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='datapumpdetail',
            name='dbinstance',
        ),
        migrations.RemoveField(
            model_name='datapumpdetail',
            name='operatelog',
        ),
        migrations.RemoveField(
            model_name='dbcluster',
            name='sysname',
        ),
        migrations.RemoveField(
            model_name='dbinstance',
            name='dbcluster',
        ),
        migrations.DeleteModel(
            name='InceptionParam',
        ),
        migrations.RemoveField(
            model_name='mhaprocessinfo',
            name='dbcluster',
        ),
        migrations.RemoveField(
            model_name='middleinstallinfo',
            name='operatelog',
        ),
        migrations.RemoveField(
            model_name='mycnftemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='mycnftemplateentry',
            name='mycnftemplate',
        ),
        migrations.RemoveField(
            model_name='mycnftemplateentry',
            name='paramItem',
        ),
        migrations.RemoveField(
            model_name='mysqlcluster',
            name='dbcluster',
        ),
        migrations.RemoveField(
            model_name='mysqlcluster',
            name='mhamanager',
        ),
        migrations.RemoveField(
            model_name='mysqlinstallinfo',
            name='operatelog',
        ),
        migrations.RemoveField(
            model_name='mysqlinstance',
            name='dbinstance',
        ),
        migrations.RemoveField(
            model_name='mysqlupgrade',
            name='dbinstance',
        ),
        migrations.RemoveField(
            model_name='mysqlupgrade',
            name='operatelog',
        ),
        migrations.DeleteModel(
            name='OperateDict',
        ),
        migrations.RemoveField(
            model_name='operatelog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='oraclecluster',
            name='dbcluster',
        ),
        migrations.RemoveField(
            model_name='oracleinstance',
            name='dbinstance',
        ),
        migrations.DeleteModel(
            name='OracleSqlCheck',
        ),
        migrations.DeleteModel(
            name='OracleSqlRule',
        ),
        migrations.DeleteModel(
            name='PlatformAccount',
        ),
        migrations.RemoveField(
            model_name='qsinfo',
            name='lvsinfo',
        ),
        migrations.RemoveField(
            model_name='qsinfo',
            name='sysname',
        ),
        migrations.DeleteModel(
            name='QsParameter',
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
        migrations.RemoveField(
            model_name='sqltask',
            name='checktasktimeset',
        ),
        migrations.RemoveField(
            model_name='sqltask',
            name='operatelog',
        ),
        migrations.RemoveField(
            model_name='sqltaskdetail',
            name='dbcluster',
        ),
        migrations.RemoveField(
            model_name='sqltaskdetail',
            name='dbinstance',
        ),
        migrations.RemoveField(
            model_name='sqltaskdetail',
            name='qsinfo',
        ),
        migrations.RemoveField(
            model_name='sqltaskdetail',
            name='sqltask',
        ),
        migrations.RemoveField(
            model_name='sysname',
            name='first_owner',
        ),
        migrations.RemoveField(
            model_name='sysname',
            name='second_owner',
        ),
        migrations.RemoveField(
            model_name='sysname',
            name='third_owner',
        ),
        migrations.RemoveField(
            model_name='taskreport',
            name='checktask',
        ),
        migrations.RemoveField(
            model_name='taskreport',
            name='operatelog',
        ),
        migrations.RemoveField(
            model_name='taskreportdbdetail',
            name='taskreport',
        ),
        migrations.RemoveField(
            model_name='taskreportitemdetail',
            name='checkitem',
        ),
        migrations.RemoveField(
            model_name='taskreportitemdetail',
            name='reportdb',
        ),
        migrations.RemoveField(
            model_name='templatedetail',
            name='checkitem',
        ),
        migrations.RemoveField(
            model_name='templatedetail',
            name='checktemplate',
        ),
        migrations.DeleteModel(
            name='AccountInfo',
        ),
        migrations.DeleteModel(
            name='CheckItem',
        ),
        migrations.DeleteModel(
            name='CheckTask',
        ),
        migrations.DeleteModel(
            name='CheckTaskDetail',
        ),
        migrations.DeleteModel(
            name='CheckTaskTimeSet',
        ),
        migrations.DeleteModel(
            name='CheckTemplate',
        ),
        migrations.DeleteModel(
            name='DataPumpDetail',
        ),
        migrations.DeleteModel(
            name='DbCluster',
        ),
        migrations.DeleteModel(
            name='DbInstance',
        ),
        migrations.DeleteModel(
            name='LVSInfo',
        ),
        migrations.DeleteModel(
            name='MHAManager',
        ),
        migrations.DeleteModel(
            name='MHAProcessInfo',
        ),
        migrations.DeleteModel(
            name='MiddleInstallinfo',
        ),
        migrations.DeleteModel(
            name='MycnfTemplate',
        ),
        migrations.DeleteModel(
            name='MycnfTemplateEntry',
        ),
        migrations.DeleteModel(
            name='MysqlCluster',
        ),
        migrations.DeleteModel(
            name='MysqlInstallinfo',
        ),
        migrations.DeleteModel(
            name='MysqlInstance',
        ),
        migrations.DeleteModel(
            name='MysqlParameter',
        ),
        migrations.DeleteModel(
            name='MysqlUpgrade',
        ),
        migrations.DeleteModel(
            name='OperateLog',
        ),
        migrations.DeleteModel(
            name='OracleCluster',
        ),
        migrations.DeleteModel(
            name='OracleInstance',
        ),
        migrations.DeleteModel(
            name='QSInfo',
        ),
        migrations.DeleteModel(
            name='SqlTask',
        ),
        migrations.DeleteModel(
            name='SqlTaskDetail',
        ),
        migrations.DeleteModel(
            name='SysName',
        ),
        migrations.DeleteModel(
            name='TaskReport',
        ),
        migrations.DeleteModel(
            name='TaskReportDbDetail',
        ),
        migrations.DeleteModel(
            name='TaskReportItemDetail',
        ),
        migrations.DeleteModel(
            name='TemplateDetail',
        ),
    ]
